-- PR5: alarms, incidents, and acknowledgement workflow
CREATE TYPE "AlarmSeverity" AS ENUM ('info', 'warning', 'major', 'critical');
CREATE TYPE "AlarmStatus" AS ENUM ('active', 'acknowledged', 'cleared', 'suppressed');
CREATE TYPE "AlarmComparator" AS ENUM ('gt', 'gte', 'lt', 'lte', 'eq', 'neq');
CREATE TYPE "IncidentStatus" AS ENUM ('open', 'investigating', 'mitigated', 'resolved', 'closed');
CREATE TABLE IF NOT EXISTS "AlarmRule" ("id" TEXT NOT NULL, "organisationId" TEXT NOT NULL, "siteId" TEXT, "plantId" TEXT, "assetId" TEXT, "name" TEXT NOT NULL, "description" TEXT, "metricKey" TEXT NOT NULL, "comparator" "AlarmComparator" NOT NULL DEFAULT 'gt', "threshold" DOUBLE PRECISION NOT NULL, "severity" "AlarmSeverity" NOT NULL DEFAULT 'warning', "enabled" BOOLEAN NOT NULL DEFAULT true, "cooldownSeconds" INTEGER NOT NULL DEFAULT 300, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AlarmRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "AlarmEvent" ("id" TEXT NOT NULL, "organisationId" TEXT NOT NULL, "siteId" TEXT NOT NULL, "plantId" TEXT, "assetId" TEXT, "ruleId" TEXT, "incidentId" TEXT, "severity" "AlarmSeverity" NOT NULL DEFAULT 'warning', "status" "AlarmStatus" NOT NULL DEFAULT 'active', "title" TEXT NOT NULL, "message" TEXT NOT NULL, "metricKey" TEXT, "metricValue" DOUBLE PRECISION, "threshold" DOUBLE PRECISION, "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "clearedAt" TIMESTAMP(3), "metadata" JSONB, CONSTRAINT "AlarmEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "AlarmAcknowledgement" ("id" TEXT NOT NULL, "alarmEventId" TEXT NOT NULL, "userId" TEXT NOT NULL, "note" TEXT, "acknowledgedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AlarmAcknowledgement_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "Incident" ("id" TEXT NOT NULL, "organisationId" TEXT NOT NULL, "siteId" TEXT NOT NULL, "plantId" TEXT, "title" TEXT NOT NULL, "summary" TEXT, "severity" "AlarmSeverity" NOT NULL DEFAULT 'major', "status" "IncidentStatus" NOT NULL DEFAULT 'open', "openedById" TEXT NOT NULL, "openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolvedAt" TIMESTAMP(3), "metadata" JSONB, CONSTRAINT "Incident_pkey" PRIMARY KEY ("id"));
CREATE TABLE IF NOT EXISTS "IncidentTimeline" ("id" TEXT NOT NULL, "incidentId" TEXT NOT NULL, "actorUserId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "message" TEXT NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "IncidentTimeline_pkey" PRIMARY KEY ("id"));
